import { useState } from 'react';
import { Button, Chip, Dialog, DialogTitle, DialogContent, DialogActions } from '@mui/material';
import { useRental } from '../contexts/RentalContext';
import { money, formatDate } from './format';
import InstrumentArt from './InstrumentArt';

export default function Reservations({ notify }) {
  const { state, dispatch } = useRental();
  const [cancelId, setCancelId] = useState(null);
  return <section className="page-section" aria-labelledby="reservations-title"><div className="section-heading"><div><span className="eyebrow">ACOMPANHE SEU PRÓXIMO SOM</span><h1 id="reservations-title">Minhas reservas</h1><p className="muted">Suas simulações ficam salvas neste navegador.</p></div><Button variant="outlined" onClick={() => dispatch({ type: 'SET_VIEW', payload: 'catalog' })}>＋ Nova reserva</Button></div>
    {!state.reservations.length ? <div className="empty-panel reservations-empty"><span className="empty-icon">♫</span><h2>Ainda não tem um som marcado?</h2><p>Escolha seus instrumentos e simule a primeira reserva.</p><Button variant="contained" onClick={() => dispatch({ type: 'SET_VIEW', payload: 'catalog' })}>Explorar catálogo</Button></div> : <div className="reservation-list">{state.reservations.map(r => <article className="reservation-card" key={r.id}><div className="reservation-top"><div><span className="eyebrow">{r.id}</span><h2>{r.customer.name}</h2></div><Chip color={r.status === 'confirmed' ? 'success' : 'default'} label={r.status === 'confirmed' ? 'Simulação confirmada' : 'Cancelada'} variant="outlined" /></div><div className="reservation-dates"><span>Retirada <strong>{formatDate(r.start)}</strong></span><span>Devolução <strong>{formatDate(r.end)}</strong></span><span>Período <strong>{r.days} {r.days === 1 ? 'diária' : 'diárias'}</strong></span></div><div className="reservation-instruments">{r.items.map(i => <div key={i.id}><span className="history-art" style={{ background: i.color }}><InstrumentArt type={i.art} /></span><span><strong>{i.name}</strong><small>{i.quantity} × {money(i.dailyPrice)} por diária</small></span></div>)}</div><div className="reservation-bottom"><p><span>Total da simulação</span><strong>{money(r.total)}</strong></p>{r.status === 'confirmed' && <Button color="error" onClick={() => setCancelId(r.id)}>Cancelar simulação</Button>}</div></article>)}</div>}
    <Dialog open={Boolean(cancelId)} onClose={() => setCancelId(null)} aria-labelledby="cancel-title"><DialogTitle id="cancel-title">Cancelar esta reserva simulada?</DialogTitle><DialogContent>As unidades serão liberadas para outras simulações nesse período. A reserva continuará no histórico como cancelada.</DialogContent><DialogActions><Button onClick={() => setCancelId(null)}>Manter reserva</Button><Button color="error" variant="contained" onClick={() => { dispatch({ type: 'CANCEL_RESERVATION', payload: cancelId }); setCancelId(null); notify('Reserva simulada cancelada.'); }}>Confirmar cancelamento</Button></DialogActions></Dialog>
  </section>;
}
